#!/usr/bin/env bash
#MISE description="Install to local Terraform plugins"
set -euo pipefail

VERSION="0.1.0"
os=$(go env GOOS)
arch=$(go env GOARCH)

go build -o "terraform-provider-truenas_v${VERSION}"

plugin_dir="$HOME/.terraform.d/plugins/registry.terraform.io/yavasura/truenas/${VERSION}/${os}_${arch}"

mkdir -p "$plugin_dir"
cp "terraform-provider-truenas_v${VERSION}" "$plugin_dir/"
echo "Installed to $plugin_dir"
